# Generated by Django 5.2.6 on 2025-09-19 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CacheEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(db_index=True, max_length=255)),
                ('original_params', models.TextField(blank=True, null=True)),
                ('function_name', models.CharField(db_index=True, max_length=255)),
                ('cache_backend', models.CharField(default='default', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('access_count', models.PositiveIntegerField(default=0)),
                ('hit_count', models.PositiveIntegerField(default=0)),
                ('miss_count', models.PositiveIntegerField(default=0)),
                ('timeout', models.PositiveIntegerField(help_text='Cache timeout in seconds')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='When this cache entry expires and should be considered invalid', null=True)),
            ],
            options={
                'verbose_name': 'Cache Entry',
                'verbose_name_plural': 'Cache Entries',
                'indexes': [models.Index(fields=['function_name', 'created_at'], name='django_smar_functio_f4cf06_idx'), models.Index(fields=['cache_key', 'last_accessed'], name='django_smar_cache_k_99d769_idx'), models.Index(fields=['expires_at'], name='django_smar_expires_9cd69e_idx'), models.Index(fields=['hit_count', 'miss_count'], name='django_smar_hit_cou_e0a490_idx'), models.Index(fields=['cache_backend', 'created_at'], name='django_smar_cache_b_a798b3_idx'), models.Index(fields=['last_accessed'], name='django_smar_last_ac_ce8318_idx')],
            },
        ),
        migrations.CreateModel(
            name='CacheEventHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(db_index=True, max_length=200)),
                ('event_type', models.CharField(choices=[('hit', 'Hit'), ('miss', 'Miss'), ('error', 'Error')], max_length=50)),
                ('cache_backend', models.CharField(default='default', max_length=100)),
                ('function_name', models.CharField(db_index=True, max_length=200)),
                ('cache_key', models.CharField(max_length=220)),
                ('occurred_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('original_params', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Cache Event',
                'verbose_name_plural': 'Cache Events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['event_name', 'occurred_at'], name='django_smar_event_n_a8e47a_idx'), models.Index(fields=['function_name', 'event_type', 'occurred_at'], name='django_smar_functio_b66168_idx')],
            },
        ),
    ]
