# Generated by Django 5.2.6 on 2025-09-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_smart_cache', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cacheentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cacheentry',
            name='last_accessed',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cacheeventhistory',
            name='occurred_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
